name: Test

on: [push]

jobs:
  test-unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        shard: [1, 2]

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run Jest (${{ matrix.shard }}/${{ strategy.job-total }})
        run: |
          yarn test --coverage --watchAll=false --shard=${{ matrix.shard }}/${{ strategy.job-total }}
          mv coverage/jest/coverage-final.json coverage/jest/${{ matrix.shard }}.json

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: jest-coverage
          path: coverage/jest

  test-ui:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run Cypress test
        uses: cypress-io/github-action@v4
        with:
          start: yarn dev
          wait-on: http://localhost:3000
          browser: chrome

      - name: Upload test run screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload test run coverage
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-coverage
          path: coverage/cypress/coverage-final.json

  coverage-report:
    needs: [test-unit, test-ui]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Download unit test coverage report
        uses: actions/download-artifact@v3
        with:
          name: jest-coverage
          path: coverage/jest

      - name: Download ui test coverage report
        uses: actions/download-artifact@v3
        with:
          name: cypress-coverage
          path: coverage/cypress

      - name: Merge coverage reports
        run: yarn test:coverage-merge
